TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/AppUser.java, TimeManagementFE/src/components/AddEntry.jsx, TimeManagementFE/src/components/AlertMessage.jsx, TimeManagementFE/src/components/EditEntry.jsx, TimeManagementFE/src/components/EntryList.jsx
Muutoksia kirjauksiin: 
- entry.title poistettu
- entry.entry nimetty uudelleen entry.comment
- jotain validointia, Date ja Time Pickerien oma validointi hyväksyy null-arvot -> fetch palauttaa virheen
Uusi AlertMessage komponentti, jota voi hyödyntää myös projektien kanssa
- 3 sekunnin timeout
- alertMessage switch EntryList komponentissa hallinnoi onnistuneen ja epäonnistuneen version, viesti propsina
=> Muutoksia kirjauksiin ja uusi AlertMessage komponentti

README.md, TimeManagementFE/src/components/AddProject.jsx, TimeManagementFE/src/components/ProjectList.jsx
Projekti lisätty onnistuneesti -ilmoitus frontendiin -- > taski tehty
Päivitä tietokantataulu // piirrä java-taulu tietokantataulun sijaan -- > Päivitin tuota readme dokkaria. En ihan ymmärtänyt mitä tuolla Java-taululla tarkoitetaan. Jos saan tarkemmat tiedot niin voin tätä taskia vielä työstää.
=> #53 Projekti lisätty onnistuneesti ja #47 Readme dokkarin päivitys

TimeManagementBE/pom.xml, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/TimeManagementBeApplication.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/WebSecurityConfig.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/AppUserRepository.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/Entry.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/EntryRepository.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/AppUserDetailsService.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/EntryRESTController.java
=> Spring Security

README.md
Jatkoa tikettiin #47 Päivitä tietokantataulu // piirrä java-taulu tietokantataulun sijaan
=> Readme dokkariin luokkien väliset listat ja FK:t lisätty

README.md, TimeManagementFE/src/components/AddProject.jsx, TimeManagementFE/src/components/EditProject.jsx
Handle close funktio lisätty ja tehty muutoksia, joista mainittiin katselmoinnissa.
=> HandleClose funktion added

TimeManagementBE/pom.xml, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/AuthEntryPoint.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/AuthenticationFilter.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/WebSecurityConfig.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/AccountCredentialsDTO.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/service/JwtService.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/LoginRESTController.java
Added JWT authentication and request filtering.
=> Backend tietojen suojaus ja kirjautuminen

TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/AuthEntryPoint.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/AuthenticationFilter.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/TimeManagementBeApplication.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/WebSecurityConfig.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/AppUser.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/Entry.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/EntryRepository.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/Project.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/ProjectRepository.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/service/AppUserDetailsService.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/service/JwtService.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/EntryRESTController.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/LoginRESTController.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/ProjectRESTController.java
- Project controllerin kaikki metodit päivitetty (toiminnot sallittu vain käyttäjän omille projekteille, myöskään tietojen peukalointi postmanilla ei pitäisi onnistua)
- Muita tiedostoja päivitetty mahdollisten virhetilanteiden varalta siten että nykyiset toiminnot tai väärä salasana/käyttäjätunnus/token eivät kaada backia eivätkä aiheuta virheilmoituksia (Hope so :D)
- Extraa: Backista lähetettävän JSONin tiedot vaihtelevat riippuen requestista (/projects lähettää projektin tiedot ilman kirjauksia, /project/{id} lähettää projektin kaikki tiedot)
=> Projektien hallinta vain projektin omistajalle ja virhetilanteiden hallintaa

TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/Entry.java, TimeManagementFE/src/components/AddEntry.jsx, TimeManagementFE/src/components/AddProject.jsx, TimeManagementFE/src/components/DeleteEntry.jsx, TimeManagementFE/src/components/DeleteProject.jsx, TimeManagementFE/src/components/EditEntry.jsx, TimeManagementFE/src/components/EditProject.jsx, TimeManagementFE/src/components/EntryList.jsx, TimeManagementFE/src/components/ProjectList.jsx, TimeManagementFE/src/services/EntryService.jsx, TimeManagementFE/src/services/ProjectService.jsx, TimeManagementFE/src/services/Routes.jsx
- token mukana kaikissa fetch pyynnöissä
- luotu ProjectService ja EntryService helpottamaan fetchien hallinnointia (kaikki pyynnöt samassa paikassa)
- lisätty JsonIgnoreProperties({"entries"}) Entry.javaan
- kaikki frontin toiminnot testattu toimiviksi
=> Lisätty autenkointi fetch pyyntöihin

TimeManagementFE/robotTests/test.robot
Päivitetty ohje jos ei ole määritellyt PATHiä niin silloin saa testin ajettua koodilla python -m robot test.robot
=> Robot test tiedostoon lisätty ohjeistus

TimeManagementFE/.gitignore
Lisäys tehty jotta virhekuvat eivät tule GitHubiin
=> robotTest screenshots added to gitignore

TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/Entry.java, TimeManagementFE/robotTests/resources.robot, TimeManagementFE/robotTests/test.robot, TimeManagementFE/src/components/AddProject.jsx, TimeManagementFE/src/components/DeleteEntry.jsx, TimeManagementFE/src/components/DeleteProject.jsx, TimeManagementFE/src/components/EditProject.jsx, TimeManagementFE/src/components/ProjectList.jsx
Lisäsin frontin projekti-tiedostoihin alert viestien käsittelyn. Se uupui. On samanlainen nyt kuin entryllä. 
Robot Frameworkin keywords ja variables siirretty omaan resource tiedostoon ja tein vähän omia kokeiluja sinne. Kaikki testit menee läpi. Uupuu vielä entryn muokkaus ja asioiden kohdistus juuri lisättyihin asioihin (ei rivin ensimmäiseen).
Poisto-testit lisätty entrylle ja projektille. Ongelma oli se että sekä sivulla että pop-upissa oli sama nimi napeilla (poista) eikä ohjelma tiennyt mitä nappia tarkoitetaan. Lisäsin nyt pop-upin nappiin poista kirjaus ja poista projekti niin nyt testit menevät läpi oikein.
=> Alert messages added to project files + Robot Framework resources file added

TimeManagementFE/robotTests/resources.robot, TimeManagementFE/robotTests/test.robot, TimeManagementFE/src/components/Home.jsx, TimeManagementFE/src/services/AppUserService.jsx
Home page -sivulle lisätty boksit, joiden kautta pääsee eri sivuille. Etunimen haku vielä kesken. Ei tällä hetkellä siis näytä käyttäjän etunimeä sivulla.
AppUserService -tiedostoon lisätty käyttäjän tietojen haku käyttäjätunnuksella
Resources.robot tiedostoon lisätty variable KirjausOnnistui
test.robot tiedostossa otettu käyttöön testeihin "kirjaus onnistui" teksti. Päivitetty myös etusivulle teksti "Hei" aiemman placeholderin sijasta.
=> Home page edited + Fetch for user + Robot test updates

TimeManagementFE/package-lock.json, TimeManagementFE/package.json, TimeManagementFE/src/components/Home.jsx, TimeManagementFE/src/components/Login.jsx
- Etusivulle lisätty nyt käyttäjän etunimen ja sukunimen näyttäminen.
- Linkki käyttäjien hallintaan päivitetty samoin teksti. Vie projektit sivulle.
- HUOM: frontti vaatii npm install komennon (jwtDecode lisätty)
- Kirjautumissivulle tehty pieniä tyylimuutoksia. Allekirjoittanut painoi liian usein vahingossa rekisteröidy nappia kun piti painaa kirjaudu nappia. Nyt kirjautuminen erottuu paremmin.
=> Home page now shows the name of the user + some style changes

README.md, TimeManagementFE/robotTests/resources.robot, TimeManagementFE/robotTests/testHeroku.robot
#143 ReadMe dokkariin lisätty tietoa julkaisusta ja testeistä. Tekstiä myös päivitetty ja linkit meidän GitHub sivuille lisätty. Näytti olevan kurssin GitHubissa maininta noista linkeistä.
#117 Robot Framework testien päivitys. Oma testi-sivu tehty julkaistulle versiolle, joka menee läpi. Lokaali vielä vaatii editProject muutokset, että toimii. Nämä muutokset seuraavat perässä vähän myöhemmin.
=> Updated Readme + RobotTests

TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/TimeManagementBeApplication.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/AppUser.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/Entry.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/EntryRepository.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/Project.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/domain/UserProjectRole.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/AppUserRESTController.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/EntryRESTController.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/ProjectRESTController.java
- Poistettu ylimääräisiä kommentteja ja turhaa koodia
- Lisätty JsonViewt lähetettävien tietojen filtteröintiin
- Muokattu responset järkevämmäksi (get palauttaa tulokset, muut yksiselitteisen vastauksen siitä mitä tapahtui)
- Lisätty testidataa CommandLineRunneriin testauksen helpottamiseksi
- Poistettu get user by id endpoint appusercontrollerista (users/id)
- Lisätty työaikaikirjausten filtteröinti roolin mukaan
- Entry controlleriin lisätty yksi try-catch lohko
=> JSON fixed + filtering results added

TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/service/AppUserDetailsService.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/AppUserRESTController.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/EntryRESTController.java, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/ProjectRESTController.java
- Uusi token luodaan ja palautetaan responsen authorization headerissa kun käyttäjä muokkaa tietojaan
- Jos käyttäjällä ei ole projekteja tai kirjauksia, palautetaan response bodyssa tyhjä lista
=> Uusi token + tyhjät listat

TimeManagementFE/robotTests/test.robot, TimeManagementFE/robotTests/testHeroku.robot, TimeManagementFE/src/components/DeleteProject.jsx, TimeManagementFE/src/components/EditProject.jsx
- Lisätty projektille käyttäjien haku, muokkaus ja poisto. 
- Varmistaa myös että projektilla on ainakin yksi owneri
- Varmistaa ettei samaa käyttäjää voi lisätä kahdesti
- Lisätty myös varoitus että projektin poisto poistaa kaikki siihen liittyvät tuntikirjaukset
- Robot Framework testeissä nyt mukana entryn lisääminen
Kehitysideoita kirjattu kommentteina editProject tiedostoon.
Huom: Poisto antaa nyt warning varoituksen null arvosta, josta on tehty uusi tiketti. Poisto kuitenkin menee läpi kuten pitääkin.
=> Projektin käyttäjien hallinta tehty

TimeManagementFE/src/components/EditProject.jsx, TimeManagementFE/src/components/Home.jsx
Käyttäjän poistaminen projektilta ei enää anna null value erroria ja pientä siistimistä.
=> Null value error korjattu käyttäjien poistamisessa projektilta

TimeManagementBE/Dockerfile, TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/EntryRESTController.java
- Dockerfile lisätty
- Try-Catch lohko palautettu EntryRESTControlleriin
=> Dockerfile + EntryRestController

TimeManagementFE/src/components/DeleteEntry.jsx, TimeManagementFE/src/components/EntryList.jsx, TimeManagementFE/src/services/EntryService.jsx
Päivitetty Entryn delete service url vastaamaan bäkin urlia.
Testattu että entryn poisto toimii.
=> Entry's delete url updated

TimeManagementFE/package-lock.json, TimeManagementFE/package.json, TimeManagementFE/src/components/TabView.jsx
Ikonien lisäys vaatii npm installin frontin toimimiseksi.
Aktiivinen välilehti ei näy korostetusti tässä versiossa, lisään jatkokehitykseen.
=> Responsiivinen navigaatio

TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/AppUserRESTController.java
POST-metodin päivitys: tietokanta heittää constraint violation errorin --> bäkki tsekkaa itse tietokannasta onko samannimista käyttäjää samalla tavalla kuin PUT metodissa
=> AppUserRESTController, POST

TimeManagementFE/src/components/AddEntry.jsx, TimeManagementFE/src/components/EditEntry.jsx
- Added validation that start_time is before end_time
- Default value for end_time is now either +6h or 23.59
- Tested manually that this works
- Also conducted Robot Framework tests, and they passed.
=> addEntry and editEntry components check that end_time is after start_time

README.md
GitHub Pages sivulla ilmenevä virhe koskien sivun päivitystä lisätty readme tiedostoon
=> Added a known error to readme
